### ISSUE TITLE
Cannot launch trackR

### ISSUE THREAD

**Issue by Gerrit79** [swarm-lab/trackR#11] opened 2018-11-24 06:25 UTC
##### System information (version)
- trackR => 0.1
- Operating System / Platform => Mac OS Mojave
- R => 3.5.1
- CMake => 3.12

##### Detailed description

When trying to launch trackR, I get the following error message:
Error in container: could not find function "container"

**Comment by Gerrit79** [comment] 2018-11-25 04:40
ROpenCVLite => 0.1.34.3
Rvision => 0.3.1
devtools => 2.0.1

**Comment by Gerrit79** [comment] 2018-11-25 23:47
shiny => 1.2.0

**Comment by sjmgarnier** [comment] 2018-11-25 23:50
@Gerrit79 Ok, this is getting a bit confusing. It looks like we have essentially the same setup, but I cannot reproduce this error here. Just to make sure, are all your packages up-to-date?

**Comment by sjmgarnier** [comment] 2018-11-25 23:53
@Gerrit79 And again just to make sure, do you have a customized .Rprofile?

**Comment by Gerrit79** [comment] 2018-11-26 02:30
Yes, all packages are up-to-date. My profile is not customized.

This is the full error message:

> trackR()
Loading required package: shiny

Attaching package: ‘Rvision’

The following objects are masked from ‘package:graphics’:

    frame, image

The following objects are masked from ‘package:base’:

    mean, merge, split, sum


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Listening on http://127.0.0.1:7361
Warning: Error in container: could not find function "container"
  70: htmlOutput

**Comment by sjmgarnier** [comment] 2018-11-27 14:47
@Gerrit79 Still digging to find the source of this problem. It's a big complicated since I don't seem to be able to reproduce it on any of my setups. 

The only place where a container function is explicitly called in trackR's code seems to be: 

```r
htmlOutput("backgroundStatus", container = p, class = "good")
```

Apparently `p` is provided by shiny through htmltools. Is htmltools installed on your system? If yes, what version do you have? 

Since it seems to be a problem with shiny/htmltools, I suggest you uninstall trackR, shiny and htmltools, and then reinstall trackR with `devtools::install_github("swarm-lab/trackR")`. This should do a clean reinstall of the 3 packages and hopefully do away with this bug.

**Comment by Gerrit79** [comment] 2018-11-28 01:21
I removed and reinstalled trackR, shiny and htmltools (0.3.6), but keep running into the same error message. 
Thanks for your help by the way!

**Comment by henry090** [comment] 2019-03-20 10:14
Hi, I have the same issue.
```
Listening on http://127.0.0.1:6373
Warning: Error in container: could not find function "container"
  70: htmlOutput
  64: moduleUI
  46: ui [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/trackR/trackR_tracktor/app.R#12]

```

**Comment by sjmgarnier** [comment] 2019-03-20 10:18
@henry090 What are the version numbers of the following: 
- trackR => :grey_question:
- Rvision => :grey_question:
- ROpenCVLite => :grey_question:
- devtools => :grey_question:
- shiny => :grey_question:
- Operating System / Platform => :grey_question:
- R => :grey_question:
- CMake => :grey_question:

**Comment by henry090** [comment] 2019-03-20 10:23
@sjmgarnier I have just updated everything (libraries) through Rstudio and it is working! =)

**Comment by sjmgarnier** [comment] 2019-03-20 10:24
@henry090 You probably just had an old version of shiny. I will close this issue now.

**Closed by sjmgarnier** 2019-03-20 10:24 UTC

**Comment by Juchartr** [comment] 2022-06-07 06:16
Hi, 

I manage to have the same problem!
 
Warning: Error in container: could not find function "container"
  92: htmlOutput
  84: moduleUI
  70: ui [C:\Users\juu19\AppData\Local\R\win-library\4.2\trackR\trackR/app.R#12]

trackR => v0.5.1
Rvision => v0.6.1
ROpenCVLite => v4.55.2
devtools => v2.4.3
shiny => v1.7.1
Operating System / Platform => windows 11
R => v4.2.0
CMake => v3.22.3

This error is only for the trackR() function and not the trackFixer() 
Do you have any idea of what could be the issue?

**Comment by sjmgarnier** [comment] 2022-06-07 07:34
@Juchartr When did you install trackR? Today?

**Comment by Juchartr** [comment] 2022-06-07 08:31
I had it for months and everything was good. I uninstalled it and install it again yesterday

**Comment by Juchartr** [comment] 2022-06-07 08:42
Yes

**Comment by sjmgarnier** [comment] 2022-06-07 08:51
@Juchartr Strange. I can't reproduce the error on any of my machines, including a Windows one with a fresh install. Are your environment clean and only the base packages loaded at startup?

**Comment by sjmgarnier** [comment] 2022-06-07 11:00
@Juchartr No problem. I'm glad it's working again.
